#!/bin/bash --login
#$ -cwd
#$ -l nvidia_v100=1
#$ -t 1-768

echo "I am config ${SGE_TASK_ID}"

module load apps/binapps/anaconda3/4.2.0
module load tools/env/proxy

source activate venv

python3 process_all_mosaics.py ${SGE_TASK_ID}
