#!/bin/bash --login
#$ -cwd
#$ -pe smp.pe 4
#$ -l nvidia_v100=1
#$ -m ea
#$ -M adam.perrett@manchester.ac.uk
#$ -t 1-96

module load apps/binapps/anaconda3/4.2.0
module load tools/env/proxy

source activate venv

python3 process_all_mosaics.py ${SGE_TASK_ID}
